#! /bin/sh
#

### BEGIN INIT INFO
# Provides:          etherpad 
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop the [etherpad program]

### END INIT INFO
#
# etherpad This is just a friendly description of
# what our init script will do.

touch /var/lock/etherpad
case "$1" in
	start)
	echo "Starting " $0
	#
	# Do something to startup the target platform here
	#
	/usr/mine/etherpad-lite/bin/run.sh 
	#sudo -u etherpad /usr/mine/etherpad-lite/bin/run.sh 
	;;

	stop)
	echo "Stopping " $0
	#
	# Do something to stop the target platform here
	#
	sudo -u etherpad /usr/mine/etherpad-lite/bin/run.sh 
	;;

	restart)
	echo "Restarting " $0
	$0 stop
	$0 start
	;;

	status)
	echo "Status Not Implemented"
	#
	# Do something to process status checks here.
	#
	;;

	*)
	echo "Usage: /etc/init.d/$0 {start|stop}"
	exit 1
	;;

esac
exit 0
